#!/usr/bin/env python3
"""Design 20.4b: silicon timing lanes for calibrating routing-delay classes.

usage: lane_timing.py gen LABMAP.json OUT.v FREQ_MHZ BUILD_ID_HEX
       lane_timing.py fit LANES.json ROUTED.json SWEEP.jsonl [MODEL.json]

One bitstream holds 22 independent lanes. Each lane launches an LFSR bit from a hand-placed register, crosses a
chain of hand-placed inverting LUTs spaced along a row, a column, a diagonal, or inside one LAB, and lands in a
hand-placed capture register whose value is folded into a lane-local 16-bit signature. After NCYC enabled cycles
each lane compares its signature with a golden computed here and reports one pass bit on the HPS gp register:
{BUILD_ID[7:0], done, locked, pass[21:0]}. Swept over the PLL frequency, each lane's first failing frequency bounds
its path delay; the routed JSON says which wires each lane used, and the fit (a later subcommand) turns the lanes
into a correction per wire class. LABMAP.json lists LAB tiles ({"lab": [[x, y], ...]}), for example from a routed
design's MISTRAL_COMB bels.
"""
import json
import sys

NCYC = 20000
LANES = 22
TAPS = (15, 13, 12, 10)


def lfsr_step(v):
    fb = 0
    for t in TAPS:
        fb ^= (v >> t) & 1
    return ((v << 1) | fb) & 0xFFFF


def misr_step(sig, bit):
    # 16-bit rotate-and-fold, the same in Verilog below
    return (((sig << 1) | (sig >> 15)) & 0xFFFF) ^ (bit * 0x8005)


def lane_plan(labs):
    """Lanes as lists of tiles (start register, hop LUTs..., capture register): (kind, tiles)."""
    lab = set(map(tuple, labs))
    cols = sorted({x for x, _ in lab})

    def row_lane(y, x0, step, hops):
        tiles, x = [], x0
        for _ in range(hops + 2):
            # snap to the next LAB column at or beyond x in this row
            nxt = [c for c in cols if c >= x and (c, y) in lab]
            if not nxt:
                return None
            tiles.append((nxt[0], y))
            x = nxt[0] + step
        return tiles

    def col_lane(x, y0, step, hops):
        # the first LAB column at or right of x whose tiles on this span are all LABs
        for c in (c for c in cols if c >= x):
            tiles = [(c, y0 + i * step) for i in range(hops + 2)]
            if all(t in lab for t in tiles):
                return tiles
        return None

    def diag_lane(x0, y0, sx, sy, hops):
        tiles, x = [], x0
        for i in range(hops + 2):
            y = y0 + i * sy
            nxt = [c for c in cols if c >= x and (c, y) in lab]
            if not nxt:
                return None
            tiles.append((nxt[0], y))
            x = nxt[0] + sx
        return tiles

    plan = []
    # rows: spans of about 3, 6 and 14 columns, short and long chains
    for i, (step, hops) in enumerate([(3, 4), (3, 10), (6, 4), (6, 8), (14, 2), (14, 4)]):
        plan.append(('row%d' % step, row_lane(22 + 2 * i, 10, step, hops)))
    # columns: spans of 2, 4 and 12 rows
    for i, (step, hops) in enumerate([(2, 5), (2, 12), (4, 4), (4, 9), (12, 2), (12, 3)]):
        plan.append(('col%d' % step, col_lane([40, 42, 43, 45, 46, 48][i], 12, step, hops)))
    # diagonals
    for i, (sx, sy, hops) in enumerate([(4, 2, 6), (8, 4, 4), (12, 6, 3), (6, 3, 7)]):
        plan.append(('diag', diag_lane(12 + 2 * i, 4 + 2 * i, sx, sy, hops)))
    # inside one LAB: a chain of LUTs over the LAB's ten ALMs, and two lanes of one hop each (register to register
    # through a LUT in the next column, the constant term's lever)
    plan.append(('local', [(37, 60)] * 10))
    plan.append(('local', [(33, 60)] * 6))
    # adjacent LABs along a row and a column: the shortest wires, in long chains
    plan.append(('row1', row_lane(64, 10, 1, 12)))
    plan.append(('col1', col_lane(36, 40, 1, 8)))
    plan.append(('short', row_lane(66, 30, 1, 1)))
    plan.append(('short', col_lane(31, 70, 1, 1)))
    assert len(plan) == LANES, len(plan)
    for kind, tiles in plan:
        assert tiles is not None and all(t in lab for t in tiles), (kind, tiles)
    return plan


def gen(labmap, out, freq, build_id):
    plan = lane_plan(json.load(open(labmap))['lab'])
    used = {}      # (x, y) -> next free ALM index
    goldens, lanes = [], []
    o = [f'// Generated by mistral/tests/lane_timing.py; design 20.4b timing lanes at {freq} MHz.',
         f"module top #(parameter [7:0] BUILD_ID = 8'h{build_id}) (input wire FPGA_CLK1_50, output wire [7:0] LED);",
         '  wire clk, lk;',
         '  altera_pll #(.reference_clock_frequency("50.0 MHz"), .number_of_clocks(1),',
         f'               .output_clock_frequency0("{freq} MHz")) p (.refclk(FPGA_CLK1_50), .rst(1\'b0), '
         '.outclk(clk), .locked(lk));',
         # The run window is a register and each lane has its own registered copy, so no enable is a long,
         # high-fanout path (the first sweep's limit near 100 MHz). Each lane still sees exactly NCYC enabled cycles.
         "  reg [15:0] n = 16'd0; reg run = 1'b0;",
         f"  always @(posedge clk) if (lk && n != 16'd{NCYC}) n <= n + 16'd1;",
         f"  always @(posedge clk) run <= lk && (n != 16'd{NCYC});",
         f'  wire [{LANES - 1}:0] pass;']
    for li, (kind, tiles) in enumerate(plan):
        seed = (0xACE1 + 0x1F3 * li) & 0xFFFF
        hops = len(tiles) - 2

        def alm_at(t):
            a = used.get(t, 0)
            used[t] = a + 1
            assert a < 10, (kind, t)
            return a
        # software model: capture(t+1) = src(t) inverted hops times; src(t+1) = lfsr bit 0 at t
        lf, src, cap, sig = seed, 0, 0, 0
        for _ in range(NCYC):
            nsig = misr_step(sig, cap)
            ncap = src ^ (hops & 1)
            nsrc = lf & 1
            lf = lfsr_step(lf)
            sig, cap, src = nsig, ncap, nsrc
        goldens.append(sig)
        a0 = alm_at(tiles[0])
        x0, y0 = tiles[0]
        o.append(f'  // lane {li}: {kind}, {hops} hops, tiles {tiles}')
        o.append(f"  reg [15:0] lf{li} = 16'h{seed:04X}; reg [15:0] sig{li} = 16'd0;")
        o.append(f"  (* keep *) reg run{li} = 1'b0; always @(posedge clk) run{li} <= run;")
        o.append(f'  always @(posedge clk) if (run{li}) lf{li} <= {{lf{li}[14:0], ' +
                 ' ^ '.join(f'lf{li}[{t}]' for t in TAPS) + '};')
        o.append(f'  wire s{li}_0;')
        o.append(f'  (* BEL="MISTRAL_FF.{x0}.{y0}.{a0 * 6 + 2}", keep *) MISTRAL_FF S{li} (.DATAIN(lf{li}[0]), '
                 f".CLK(clk), .ACLR(1'b1), .ENA(run{li}), .SCLR(1'b0), .SLOAD(1'b0), .SDATA(1'b0), .Q(s{li}_0));")
        prev = f's{li}_0'
        for h, t in enumerate(tiles[1:-1]):
            a = alm_at(t)
            w = f's{li}_{h + 1}'
            o.append(f'  wire {w};')
            o.append(f'  (* BEL="MISTRAL_COMB.{t[0]}.{t[1]}.{a * 6}", keep *) MISTRAL_NOT H{li}_{h} '
                     f'(.A({prev}), .Q({w}));')
            prev = w
        xe, ye = tiles[-1]
        ae = alm_at(tiles[-1])
        o.append(f'  wire c{li};')
        o.append(f'  (* BEL="MISTRAL_FF.{xe}.{ye}.{ae * 6 + 2}", keep *) MISTRAL_FF C{li} (.DATAIN({prev}), '
                 f".CLK(clk), .ACLR(1'b1), .ENA(run{li}), .SCLR(1'b0), .SLOAD(1'b0), .SDATA(1'b0), .Q(c{li}));")
        o.append(f"  always @(posedge clk) if (run{li}) sig{li} <= {{sig{li}[14:0], sig{li}[15]}} ^ "
                 f"({{16{{c{li}}}}} & 16'h8005);")
        o.append(f"  assign pass[{li}] = (sig{li} == 16'h{sig:04X});")
        lanes.append({'lane': li, 'kind': kind, 'hops': hops, 'tiles': tiles, 'golden': sig})
    o += ["  wire done = lk && (n == 16'd%d) && !run;" % NCYC,
          '  wire [31:0] gp_to_arm = {BUILD_ID, done, lk, pass};',
          '  wire [31:0] gp_from_arm;',
          '  cyclonev_hps_interface_mpu_general_purpose hps_gp (.gp_in(gp_to_arm), .gp_out(gp_from_arm));',
          "  assign LED = {done, lk, pass[5:0]};",
          'endmodule',
          '(* blackbox *) module altera_pll #(parameter reference_clock_frequency="50.0 MHz", '
          'parameter number_of_clocks=1,',
          '    parameter output_clock_frequency0="100.0 MHz") (input wire refclk, input wire rst, '
          'output wire outclk, output wire locked);',
          'endmodule',
          '(* blackbox *) module cyclonev_hps_interface_mpu_general_purpose (input wire [31:0] gp_in, '
          'output wire [31:0] gp_out);',
          'endmodule', '']
    open(out, 'w').write('\n'.join(o))
    json.dump({'freq': freq, 'build_id': build_id, 'ncyc': NCYC, 'lanes': lanes},
              open(out.rsplit('.', 1)[0] + '.lanes.json', 'w'), indent=1)
    print(f'{LANES} lanes, hops {[l["hops"] for l in lanes]}')


def achieved_mhz(vco, req):
    """The PLL output: the VCO over the integer counter nearest to it."""
    return vco / max(1, round(vco / req))


def fit(lanes_json, routed_json, sweep_jsonl, model_json=None):
    """Per-lane silicon delay bounds from a sweep, and a least-squares fit of per-class wire delays."""
    import collections
    import re
    plan = json.load(open(lanes_json))['lanes']
    m = list(json.load(open(routed_json))['modules'].values())[0]
    comp = {}
    for l in plan:
        li, c = l['lane'], collections.Counter()
        for n, nn in m['netnames'].items():
            if re.fullmatch(rf's{li}_\d+', n) or n.startswith(f'C{li}$ROUTETHRU'):
                for w in nn['attributes'].get('ROUTING', '').split(';')[0::3]:
                    if w:
                        c[w.split('.')[0]] += 1
        comp[li] = c
    points = []
    for line in open(sweep_jsonl):
        r = json.loads(line)
        mm = re.search(r'done=1 locked=1 pass=([01]{%d})' % LANES, r['result'])
        if not mm:
            continue  # a void point (no readout, not locked, not done)
        bits = mm.group(1)
        points.append((achieved_mhz(r['vco'], r['req']), {li: bits[LANES - 1 - li] == '1' for li in range(LANES)}))
    points.sort()
    model = {r['lane']: r for r in json.load(open(model_json))} if model_json else {}
    rows = []
    for l in plan:
        li = l['lane']
        # the highest frequency below which every point passes, and the first failure above it
        f_pass, f_fail = None, None
        for f, ok in points:
            if ok[li] and f_fail is None:
                f_pass = f
            elif not ok[li] and f_fail is None:
                f_fail = f
        flips = sum(1 for f, ok in points if f_fail is not None and f > f_fail and ok[li])
        if f_pass is None:
            continue
        t_hi = 1000.0 / f_pass
        t_lo = 1000.0 / f_fail if f_fail else None
        t = (t_hi + t_lo) / 2 if t_lo else None
        rows.append((li, l['kind'], l['hops'], f_pass, f_fail, flips, t, comp[li], model.get(li, {})))
    cls = ['H3', 'H6', 'V2']
    fitted = [r for r in rows if r[6] is not None]
    x = []
    for li, kind, hops, fp, ff, fl, t, c, mo in fitted:
        longw = c.get('H14', 0) + c.get('V4', 0) + c.get('V12', 0)
        x.append([1.0, float(hops)] + [float(c.get(k, 0)) for k in cls] + [float(longw)])
    names = ['constant', 'per hop (LUT + exit/entry)'] + [f'{k} wire' for k in cls] + ['long wire (H14/V4/V12)']
    coef = None
    if len(fitted) > len(names):
        # normal equations with a small ridge, solved by Gaussian elimination (no numpy needed)
        n = len(names)
        ata = [[sum(r[i] * r[j] for r in x) + (1e-6 if i == j else 0) for j in range(n)] for i in range(n)]
        atb = [sum(r[i] * f[6] for r, f in zip(x, fitted)) for i in range(n)]
        for col in range(n):
            piv = max(range(col, n), key=lambda k: abs(ata[k][col]))
            ata[col], ata[piv], atb[col], atb[piv] = ata[piv], ata[col], atb[piv], atb[col]
            for k in range(n):
                if k != col and ata[col][col]:
                    fct = ata[k][col] / ata[col][col]
                    ata[k] = [a - fct * b for a, b in zip(ata[k], ata[col])]
                    atb[k] -= fct * atb[col]
        coef = [atb[i] / ata[i][i] for i in range(n)]
    print(f'{"lane":>4} {"kind":6} {"hops":>4} {"pass MHz":>8} {"fail MHz":>8} {"flips":>5} {"silicon ns":>10} '
          f'{"fit ns":>7} {"model ns":>8} {"pins ns":>7}')
    for (li, kind, hops, fp, ff, fl, t, c, mo), *_ in zip(rows):
        pred = None
        if coef and t is not None:
            longw = c.get('H14', 0) + c.get('V4', 0) + c.get('V12', 0)
            xr = [1.0, float(hops)] + [float(c.get(k, 0)) for k in cls] + [float(longw)]
            pred = sum(a * b for a, b in zip(coef, xr))
        fmt = lambda v, w=7: (f'{v:{w}.2f}' if v is not None else ' ' * (w - 1) + '-')
        print(f'{li:4d} {kind:6} {hops:4d} {fmt(fp, 8)} {fmt(ff, 8)} {fl:5d} {fmt(t, 10)} {fmt(pred)} '
              f'{fmt(mo.get("model_default_ns"), 8)} {fmt(mo.get("model_pins_ns"))}')
    if coef:
        print('fit (ns):', ', '.join(f'{nm} {v:.3f}' for nm, v in zip(names, coef)))


if __name__ == '__main__':
    if len(sys.argv) == 6 and sys.argv[1] == 'gen':
        gen(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
    elif len(sys.argv) in (5, 6) and sys.argv[1] == 'fit':
        fit(*sys.argv[2:])
    else:
        print(__doc__)
        sys.exit(1)
