#!/usr/bin/env python3
"""Generate mistral/span_delay.h, the placement delay table of design 19.8.

usage: span_delay.py OUT.h ARCS.csv...

Each ARCS.csv is a MISTRAL_DUMP_ARC_DELAYS dump of a routed design (net, driver x/y, sink x/y, routing
delay in ns). The table holds, per span (|dx|, |dy|), the median routed delay in picoseconds. A span
with fewer than MIN_ARCS arcs takes the median of its neighbourhood, widened until it has enough; the
table is then made non-decreasing in dx and in dy, so that moving a sink away never predicts less.
"""
import collections
import csv
import os
import statistics
import sys

DX, DY = 92, 82   # spans covered (the 5CSEBA6 grid is 89 by 81); beyond them the arch extrapolates
MIN_ARCS = 20

out, sources = sys.argv[1], sys.argv[2:]
spans = collections.defaultdict(list)
for path in sources:
    for r in csv.DictReader(open(path)):
        dx = abs(int(r['dx0']) - int(r['sx']))
        dy = abs(int(r['dy0']) - int(r['sy']))
        if dx < DX and dy < DY:
            spans[(dx, dy)].append(float(r['delay_ns']))


def median_near(dx, dy):
    for rad in range(0, 12):
        v = [x for i in range(max(0, dx - rad), min(DX, dx + rad + 1))
             for j in range(max(0, dy - rad), min(DY, dy + rad + 1)) for x in spans.get((i, j), ())]
        if len(v) >= MIN_ARCS:
            return statistics.median(v)
    return None


table = [[median_near(dx, dy) for dy in range(DY)] for dx in range(DX)]
# Spans with no data anywhere near: carry the nearest smaller span forward (the monotone pass below lifts them).
for dx in range(DX):
    for dy in range(DY):
        if table[dx][dy] is None:
            table[dx][dy] = max(table[dx - 1][dy] if dx else 0.0, table[dx][dy - 1] if dy else 0.0)
for dx in range(DX):
    for dy in range(DY):
        table[dx][dy] = max(table[dx][dy], table[dx - 1][dy] if dx else 0.0, table[dx][dy - 1] if dy else 0.0)

arcs = sum(len(v) for v in spans.values())
with open(out, 'w') as f:
    f.write('// Generated by mistral/tests/span_delay.py; do not edit. Design 19.8: the median routed delay by span\n')
    f.write(f'// in picoseconds, from {arcs} routed arcs of: {", ".join(os.path.basename(s) for s in sources)}.\n')
    f.write('#ifndef MISTRAL_SPAN_DELAY_H\n#define MISTRAL_SPAN_DELAY_H\n\n#include <cstdint>\n\n')
    f.write('#include "nextpnr_namespaces.h"\n\nNEXTPNR_NAMESPACE_BEGIN\n\n')
    f.write(f'static constexpr int SPAN_DELAY_DX = {DX}, SPAN_DELAY_DY = {DY};\n')
    f.write('// clang-format off\n')
    f.write('static constexpr uint16_t span_delay_ps[SPAN_DELAY_DX][SPAN_DELAY_DY] = {\n')
    for dx in range(DX):
        f.write('        {' + ', '.join(str(int(round(v * 1000))) for v in table[dx]) + '},\n')
    f.write('};\n// clang-format on\n\nNEXTPNR_NAMESPACE_END\n\n#endif\n')
print(f'{out}: {DX}x{DY} spans from {arcs} arcs; (1,0) {table[1][0]:.2f} (0,1) {table[0][1]:.2f} '
      f'(10,0) {table[10][0]:.2f} (0,20) {table[0][20]:.2f} ns')
